In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.DataFrame([ {"n_chambres" : 2, "superficie" : 40, "prix" : 10},
                     {"n_chambres" : 4,"superficie" : 35,  "prix" : 20},
                    {"n_chambres" : 3,"superficie" : 21,  "prix" : 15},
                     {"n_chambres" : 3,"superficie" : 18,  "prix" : 20},
                     {"n_chambres" : 1,"superficie" : 53,  "prix" : 3.5},
                    {"n_chambres" : 6,"superficie" : 75,  "prix" : 31},
                     {"n_chambres" : 5,"superficie" : 10,  "prix" : 33},
                    {"n_chambres" : 8,"superficie" : 46,  "prix" : 36},
                    {"n_chambres" : 7,"superficie" : 17,  "prix" : 50},
                    {"n_chambres" : 9,"superficie" : 100,  "prix" : 42},
                    ])
data

n_chambres  superficie  prix
0           2          40  10.0
1           4          35  20.0
2           3          21  15.0
3           3          18  20.0
4           1          53   3.5
5           6          75  31.0
6           5          10  33.0
7           8          46  36.0
8           7          17  50.0
9           9         100  42.0

In [6]:
X = data[["n_chambres", "superficie"]].values
X

array([[  2,  40],
       [  4,  35],
       [  3,  21],
       [  3,  18],
       [  1,  53],
       [  6,  75],
       [  5,  10],
       [  8,  46],
       [  7,  17],
       [  9, 100]])

In [7]:
X.shape

(10, 2)

In [8]:
X.ndim # matrice # tenseur # tensor # tensorflow

2

In [9]:
n_chambre = data['n_chambres'].values

In [10]:
n_chambre.ndim # vecteur

1

In [12]:
np.array([X, X,X]).shape # tenseur

(3, 10, 2)

In [13]:
np.array([X, X,X]).ndim

3

In [14]:
maison = [[  2,  40],
       [  4,  35],
       [  3,  21],
       [  3,  18]]
weights = [0.23, 3]

In [16]:
prix = 0
for x, w in zip(maison, weights):
  prix = prix + x*w
prix

18.46

In [17]:
maison = np.array([
    [2, 1, 3],
    [0, -1, 4],
    [3, 1, -5]
])

In [18]:
maison.shape

(3, 3)

In [19]:
W = np.array([2, 1, 3])

In [20]:
y = np.dot(maison, W)

In [21]:
y

array([14, 11, -8])

In [22]:
y.shape

(3,)

In [23]:
x = np.array([
    [1, 0, 2],
    [3, -1, 2]
])

In [24]:
x.shape

(2, 3)

In [25]:
x.T

array([[ 1,  3],
       [ 0, -1],
       [ 2,  2]])

In [26]:
x.T.shape

(3, 2)

In [ ]:
dm_dw = X.T

dm_dx = W.T