In [3]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [5]:
folder = '/gdrive/MyDrive/deep_learning_course/data/'

In [4]:
!ls '/gdrive/MyDrive/deep_learning_course/data/'

archive.zip  Bible_fra.txt  tweets


In [6]:
with open(folder + "Bible_fra.txt", "r") as f:
  lines = f.readlines()

In [7]:
len(lines)

41899

In [7]:
lines[45]

'L’Éternel Dieu prit l’homme, et le plaça dans le jardin d’Éden pour le cultiver et pour le garder.\n'

In [8]:
lines[6]

'Et Dieu fit l’étendue, et il sépara les eaux qui sont au-dessous de l’étendue d’avec les eaux qui sont au-dessus de l’étendue. Et cela fut ainsi.\n'

In [12]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

# Nettoyage du corpus

In [14]:
lines[0]

'Au commencement, Dieu créa les cieux et la terre.\n'

In [55]:
corpus = []
for line in lines:
  line = line.split('\n')[0]
  line = line.lower()
  if line:
    corpus.append(line)

In [17]:
lines[41000].split('\n')[0]

''

In [18]:
bool(lines[41000].split('\n')[0])

False

In [20]:
len(corpus)

31055

In [56]:
corpus = corpus[:7000]

# Tokenisation

In [22]:
corpus[45]

'l’éternel dieu prit l’homme, et le plaça dans le jardin d’éden pour le cultiver et pour le garder.'

In [57]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [58]:
tokenizer = Tokenizer()

In [59]:
tokenizer.fit_on_texts(corpus)

In [60]:
len(tokenizer.word_index)

9420

In [27]:
corpus[3]

'dieu vit que la lumière était bonne; et dieu sépara la lumière d’avec les ténèbres.'

In [30]:
seq = tokenizer.texts_to_sequences([corpus[3]])[0]

In [31]:
seq

[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284, 5, 1542]

In [33]:
for i in range(1, len(seq)):
  print(seq[:i+1])

[27, 279]
[27, 279, 10]
[27, 279, 10, 4]
[27, 279, 10, 4, 1840]
[27, 279, 10, 4, 1840, 78]
[27, 279, 10, 4, 1840, 78, 1102]
[27, 279, 10, 4, 1840, 78, 1102, 1]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284, 5]
[27, 279, 10, 4, 1840, 78, 1102, 1, 27, 2660, 4, 1840, 2284, 5, 1542]


In [61]:
sequences = tokenizer.texts_to_sequences(corpus)

In [62]:
input_sequences = []

for seq in sequences:
  for i in range(1, len(seq)):
    data_line = seq[:i+1]
    input_sequences.append(data_line)

In [63]:
len(input_sequences)

163770

In [38]:
input_sequences[7:12]

[[29, 2046, 27, 1541, 5, 549, 1, 4, 91],
 [4, 91],
 [4, 91, 78],
 [4, 91, 78, 5561],
 [4, 91, 78, 5561, 1]]

# Padding

In [64]:
max([len(x) for x in input_sequences])

66

In [65]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [67]:
input_sequences = pad_sequences(input_sequences, padding="pre", maxlen=66)

In [42]:
input_sequences[7:12]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,   29, 2046,   27, 1541,    5,  549,    1,    4,   91],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    4,   91],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0

# Creating x_train et y_train

In [68]:
input_sequences.shape

(163770, 66)

In [69]:
x_train = input_sequences[:, :-1]
y_train = input_sequences[:, -1]

In [70]:
x_train.shape, y_train.shape

((163770, 65), (163770,))

In [48]:
x_train[6]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,   29, 2046,   27, 1541,    5,  549,    1],
      dtype=int32)

In [49]:
y_train[6]

4

In [71]:
import tensorflow as tf

In [52]:
tf.keras.utils.to_categorical([4, 2, 1])

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

In [72]:
y_train = tf.keras.utils.to_categorical(y_train)

In [54]:
y_train[6]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [73]:
y_train.shape

(163770, 9421)

# Modeling

In [17]:
import numpy as np

In [57]:
np.power(66, 1/4)

2.8502698827717983

In [74]:

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Embedding(9421, 16),
        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
        tf.keras.layers.Dense(9421, activation='softmax'),

    ]
)

model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])


In [75]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 16)          150736    
                                                                 
 bidirectional_2 (Bidirectio  (None, 128)              41472     
 nal)                                                            
                                                                 
 dense_2 (Dense)             (None, 9421)              1215309   
                                                                 
Total params: 1,407,517
Trainable params: 1,407,517
Non-trainable params: 0
_________________________________________________________________


In [76]:
h = model.fit(x_train, y_train, epochs=20, batch_size=1024)

Epoch 1/20
160/160 [==============================] - 38s 208ms/step - loss: 6.9277 - accuracy: 0.0455
Epoch 2/20
160/160 [==============================] - 17s 103ms/step - loss: 6.4198 - accuracy: 0.0482
Epoch 3/20
160/160 [==============================] - 13s 79ms/step - loss: 6.2315 - accuracy: 0.0566
Epoch 4/20
160/160 [==============================] - 12s 76ms/step - loss: 6.0875 - accuracy: 0.0660
Epoch 5/20
160/160 [==============================] - 11s 68ms/step - loss: 5.9812 - accuracy: 0.0725
Epoch 6/20
160/160 [==============================] - 11s 67ms/step - loss: 5.8997 - accuracy: 0.0769
Epoch 7/20
160/160 [==============================] - 10s 58ms/step - loss: 5.8288 - accuracy: 0.0814
Epoch 8/20
160/160 [==============================] - 10s 62ms/step - loss: 5.7494 - accuracy: 0.0858
Epoch 9/20
160/160 [==============================] - 9s 59ms/step - loss: 5.6637 - accuracy: 0.0943
Epoch 10/20
160/160 [==============================] - 9s 53ms/step - loss: 5.584

# Generer du Texte

In [77]:
x_train.shape

(163770, 65)

In [78]:
prompt = "dieu est"

In [79]:
prompt_seq = tokenizer.texts_to_sequences([prompt])
prompt_seq

[[27, 45]]

In [80]:
prompt_seq[0]

[27, 45]

In [81]:
prompt_x = pad_sequences([prompt_seq[0]], padding="pre", maxlen=65)

In [82]:
prompt_x.shape

(1, 65)

In [83]:
prompt_x

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 27,
        45]], dtype=int32)

In [84]:
pred = model.predict(prompt_x)

1/1 [==============================] - 1s 642ms/step


In [85]:
pred

array([[2.3151680e-08, 1.0431145e-02, 2.7218347e-02, ..., 3.6895756e-06,
        1.5638627e-06, 2.5165618e-06]], dtype=float32)

In [86]:
import numpy as np

In [87]:
np.argmax(pred)

18

In [ ]:
tokenizer.index_word

In [88]:
tokenizer.index_word.get(18)

'un'

In [95]:
prompt = "La tente d'assignation"

n_predict = 10

for _ in range(n_predict):
  prompt_seq = tokenizer.texts_to_sequences([prompt])
  prompt_x = pad_sequences([prompt_seq[0]], padding="pre", maxlen=65)
  pred = model.predict(prompt_x)
  index = np.argmax(pred)
  mot_predit = tokenizer.index_word.get(index)
  print(prompt + " " + mot_predit)
  prompt = prompt + " " + mot_predit

1/1 [==============================] - 0s 34ms/step
La tente d'assignation d’assignation
1/1 [==============================] - 0s 31ms/step
La tente d'assignation d’assignation de
1/1 [==============================] - 0s 45ms/step
La tente d'assignation d’assignation de la
1/1 [==============================] - 0s 40ms/step
La tente d'assignation d’assignation de la tente
1/1 [==============================] - 0s 22ms/step
La tente d'assignation d’assignation de la tente d’assignation
1/1 [==============================] - 0s 19ms/step
La tente d'assignation d’assignation de la tente d’assignation de
1/1 [==============================] - 0s 19ms/step
La tente d'assignation d’assignation de la tente d’assignation de la
1/1 [==============================] - 0s 20ms/step
La tente d'assignation d’assignation de la tente d’assignation de la tente
1/1 [==============================] - 0s 20ms/step
La tente d'assignation d’assignation de la tente d’assignation de la tente d’assignation
1

In [91]:
corpus[36]

'mais une vapeur s’éleva de la terre, et arrosa toute la surface du sol.'

In [ ]:
90